FROM debian:buster

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y \
    openssh-server \
    && rm -rf /var/lib/apt/lists/*

RUN bash -c 'echo -e "root\nroot\n" | passwd root'
RUN mkdir /var/run/sshd
RUN sed -i 's,^#\?PermitRootLogin .*,PermitRootLogin yes,g' /etc/ssh/sshd_config
EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
